version: '3.8'

services:
  # redis service
  redis:
    image: redis
    ports:
      - 6379:6379
      
  # main database 
  postgres:
    build: ./db
    restart: always
    volumes: 
      - ./data:/data
    environment: 
      - POSTGRES_USER=payment
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWROD=payment
      - POSTGRES_DB=payment_db 
    ports:
      - 5432:5432
    
  # auth service
  auth:
    build: ./payment-system-auth
    command: ./app
    ports:
      - 8111:8111
    depends_on: 
      - redis
      - postgres
    links:
      - redis
      - postgres

  # parsing service

  #  
    


    

